nodeLinker: pnp

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'
  # typegoose-cursor-pagination@*:
  #   dependencies:
  #     types/mongoose: '*'

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: 'https://yarn.build/latest'

yarnPath: .yarn/releases/yarn-3.1.0.cjs
