yarnPath: .yarn/releases/yarn-3.1.0.cjs

nodeLinker: node-modules

packageExtensions:
  ts-jest@*:
    peerDependencies:
      jest: '*'
  ts-node@^10.2.1:
    peerDependencies:
      '@types/node': '*'
