nodeLinker: pnp

# packageExtensions:
#   ts-jest@*:
#     peerDependencies:
#       jest: '*'
#   ts-node@^10.2.1:
#     peerDependencies:
#       '@types/node': '*'
#   eslint-module-utils@*:
#     dependencies:
#       eslint-import-resolver-node: '*'

plugins:
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: 'https://yarn.build/latest'

yarnPath: .yarn/releases/yarn-3.1.0.cjs
