version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '4001:4000'
    container_name: demo_nodejs-api
    links:
      - mongo-db
  mongo-db:
    image: mongo:latest
    container_name: demo_mongo-db
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
