version: '3.7'
services:
  mongo-db-dev:
    image: mongo:latest
    container_name: demo_mongo-db-dev
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27016:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
